theme: jekyll-theme-cayman
title: Madhu's Blog
description: Thoughts on AI, Technology, and the Future
author: Madhu

# Social links (optional)
github_username: https://github.com/Madhuvod
# twitter_username: your-twitter-handle

# Blog settings
show_excerpts: true
future: true
